# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ rewrite ]
  pull_request:
    branches: [ rewrite ]

env:
  lts: 14
  latest: 16

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.lts }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.lts }}

    - name: Get npm cache directory
      id: npm-cache-dir
      run: echo "::set-output name=dir::$(npm config get cache)"
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ env.lts }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ env.lts }}-
          ${{ runner.os }}-node-
          ${{ runner.os }}-

    - run: npm ci
    - run: npm run lint
    - run: npm run check-type
    - run: npm test

  build:
    needs: test

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [12, 14, 16]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}

    - name: Get npm cache directory
      id: npm-cache-dir
      run: echo "::set-output name=dir::$(npm config get cache)"
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ matrix.node }}-
          ${{ runner.os }}-node-
          ${{ runner.os }}-

    - run: npm ci
    - run: npm run build:dev

  # deploy:
  #   if: ${{  }}
  #   needs: build

  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Use Node.js ${{ env.lts }}
  #     uses: actions/setup-node@v2
  #     with:
  #       node-version: ${{ env.lts }}

  #   - name: Get npm cache directory
  #     id: npm-cache-dir
  #     run: echo "::set-output name=dir::$(npm config get cache)"
  #   - name: Cache node modules
  #     uses: actions/cache@v2
  #     with:
  #       path: ${{ steps.npm-cache-dir.outputs.dir }}
  #       key: ${{ runner.os }}-node-${{ env.lts }}-${{ hashFiles('**/package-lock.json') }}
  #       restore-keys: |
  #         ${{ runner.os }}-node-${{ env.lts }}-
  #         ${{ runner.os }}-node-
  #         ${{ runner.os }}-

  #   - run: npm ci
  #   - run: npm run build:prod
  #   - uses: actions/upload-artifact@v2
  #     with:
  #       name: scripts
  #       path: dist/
