# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - rewrite
  pull_request:
    branches:
      - rewrite

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: lts/*
        cache: npm
    - run: npm ci
    - run: npm run lint
    - run: npm run check-type
    - run: npm test

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: lts/*
        cache: npm
    - run: npm ci
    - run: npm run build:dev
    - uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/

  # deploy:
  #   if: ${{  }}
  #   needs: build

  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-node@v2
  #     with:
  #       node-version: lts/*
  #       cache: npm
  #   - run: npm ci
  #   - run: npm run build:prod
  #   - uses: actions/upload-artifact@v2
  #     with:
  #       name: scripts
  #       path: dist/
